version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - mynet
    volumes: 
      - mongo_data:/data/db
  moviehubserver:
    image: moviehubserver
    container_name: movie-hub
    ports: 
      - "3000:3000"
    networks:
      - mynet
    volumes: 
      - moviehub_data:/usr/share/moviehub/data
    environment:
      - DEBUG=1
      - MONGO_HOST=mongo
    depends_on:
      - mongo
networks:
  mynet:
    driver: bridge
volumes:
  mongo_data:
  moviehub_data: